#클래스

파이썬 외 프로그래밍 언어
- 계열 언어
- 자바 (JS 포함)
- PHP
- 루비
- 스칼라
- 스위프트

C 를 제외하고 모두 객체 지향 프로그래밍 언어

객체 지향 프로그래밍 언어
- 객체를 우선으로 생각하는 프로그래밍
- 클래스 기반

In [5]:
# 객체 생성
students = [
    {"name":"강명호","korean":80,"math":70,"english":60,"science":100},
    {"name":"최수원","korean":50,"math":40,"english":100,"science":70},
    {"name":"이연경","korean":40,"math":70,"english":42,"science":80},
    {"name":"김유정","korean":42,"math":62,"english":72,"science":86},
    {"name":"양채연","korean":75,"math":56,"english":52,"science":54},
    {"name":"박지인","korean":61,"math":78,"english":72,"science":52},
    
]
print("이름","총점","평균",sep="\t")
for student in students:
  score_sum = student["korean"]+student["math"]+\
  student["english"]+student["science"]

  score_mean = score_sum / 4
  print(student["name"], score_sum, score_mean, sep = "\t")

이름	총점	평균
강명호	310	77.5
최수원	260	65.0
이연경	232	58.0
김유정	262	65.5
양채연	237	59.25
박지인	263	65.75

In [8]:
# 객체 생성
def create_student(name, korean, math, english, science):
  return {
      "name":name,
      "korean": korean,
      "math": math,
      "english": english,
      "science": science
  }

students = [
create_student("강명호",80,70,60,100),
create_student("최수원",50,40,100,70),
create_student("이연경",40,70,42,80),
create_student("김유정",42,62,72,86),
create_student("양채연",75,56,52,54),
create_student("박지인",61,78,72,52)
]

print("이름","총점","평균",sep="\t")
for student in students:
  score_sum = student["korean"]+student["math"]+\
  student["english"]+student["science"]

  score_mean = score_sum / 4
  print(student["name"], score_sum, score_mean, sep = "\t")

이름	총점	평균
강명호	310	77.5
최수원	260	65.0
이연경	232	58.0
김유정	262	65.5
양채연	237	59.25
박지인	263	65.75

In [11]:
# 객체 생성
def create_student(name, korean, math, english, science):
  return {
      "name":name,
      "korean": korean,
      "math": math,
      "english": english,
      "science": science
  }
def sutdent_sum(student):
  return student["korean"]+student["math"]+\
  student["english"]+student["science"]

def student_mean(student):
  return student_sum(student) / 4

def student_print(student):
  return "{}\t{}\t{}".format(student["name"], 
                             score_sum(student), 
                             score_mean(student)
      
  )
  

students = [
create_student("강명호",80,70,60,100),
create_student("최수원",50,40,100,70),
create_student("이연경",40,70,42,80),
create_student("김유정",42,62,72,86),
create_student("양채연",75,56,52,54),
create_student("박지인",61,78,72,52)
]

print("이름","총점","평균",sep="\t")
for student in students:
  print(student["name"], score_sum, score_mean, sep = "\t")

이름	총점	평균
강명호	263	65.75
최수원	263	65.75
이연경	263	65.75
김유정	263	65.75
양채연	263	65.75
박지인	263	65.75

## 클래스

객체를 조금 더 효율적으로 생성할 수 있도록 도와주는 개념

    class 클래스이름: 
      클래스 내용

클래스 이름은 캐멀 케이스 작성(함수 이름과 구별하기 위해)

    인스턴스 이름(변수 이름) = 클래스 이름()

In [44]:
# 클래스
class Student:
    def __init__(self, name, korean, math, english, science):
        self.name = name
        self.korean = korean
        self.math = math
        self.english = english
        self.science = science

    def score_sum(self):
        return self.korean + self.math + self.english + self.science

    def score_mean(self):
        return self.score_sum() / 4

    def print_info(self):
        print("{}\t{}\t{}".format(self.name, self.score_sum(), self.score_mean()))

students = [
    Student("강명호", 80, 70, 60, 100),
    Student("최수원", 50, 40, 100, 70),
    Student("이연경", 40, 70, 42, 80),
    Student("김유정", 42, 62, 72, 86),
    Student("양채연", 75, 56, 52, 54),
    Student("박지인", 61, 78, 72, 52)
]

print("이름", "총점", "평균", sep="\t")
for student in students:
    student.print_info()

이름	총점	평균
강명호	310	77.5
최수원	260	65.0
이연경	232	58.0
김유정	262	65.5
양채연	237	59.25
박지인	263	65.75

In [43]:
# 메소드
class Student:
  def __init__(self, name, kor, math, eng, sci):
     self.name = name
     self.kor = kor
     self.math = math
     self.eng = eng
     self.sci = sci
  # 학생 점수 합을 구하는 메소드
  def student_sum(self):
    return  self.kor + self.math + \
            self.eng + self.sci
  # 학생 평균 점수 구하는 메소드
  def student_mean(self):
    return self.student_sum() / 4
  # 출력하는 메소드
  def student_print(self):
    return "{}\t{}\t{}".format(self.name, self.student_sum(), self.student_mean())
students = [
    Student("강명호", 80, 70, 60, 100),
    Student("최수원", 50, 40, 100, 70),
    Student("이연경", 40, 80, 80, 80),
    Student("김유정", 80, 90, 70, 50),
    Student("양채연", 90, 80, 50, 80),
    Student("박지인", 50, 40, 90, 90)
    ]
print("이름", "총점", "평균", sep = "\t")
for student in students:
  print(student.student_print())

이름	총점	평균
강명호	310	77.5
최수원	260	65.0
이연경	280	70.0
김유정	290	72.5
양채연	300	75.0
박지인	270	67.5

In [39]:
# 메소드
class Student:
    def __init__(self, name, korean, math, english, science):
        self.name = name
        self.korean = korean
        self.math = math
        self.english = english
        self.science = science

    def score_sum(self):
        return self.korean + self.math + self.englis0h + self.science

    def score_mean(self):
        return self.score_sum() / 4

    def print_info(self):
        print("{}\t{}\t{}".format(self.name, self.score_sum(), self.score_mean()))

# List of students
students = [
    Student("강명호", 80, 70, 60, 100),
    Student("최수원", 50, 40, 100, 70),
    Student("이연경", 40, 70, 42, 80),
    Student("김유정", 42, 62, 72, 86),
    Student("양채연", 75, 56, 52, 54),
    Student("박지인", 61, 78, 72, 52)
]

# Print header
print("이름", "총점", "평균", sep="\t")

# Print student information
for student in students:
    student.print_info()

이름	총점	평균
강명호	310	77.5
최수원	260	65.0
이연경	232	58.0
김유정	262	65.5
양채연	237	59.25
박지인	263	65.75