In [2]:
# 판다스 자료 구조
# 시리즈
# 판다스 불러오기 
import pandas as pd
# 딕셔너리 만들기
dict_data = {"a":1,
             "b":2,
             "c":3}
print(dict_data)

{'a': 1, 'b': 2, 'c': 3}

In [4]:
# 시리즈 만들기
sr = pd.Series(dict_data)
print(sr)

a    1
b    2
c    3
dtype: int64

In [6]:
# 시리즈 객체인지 확인
print(type(sr))

<class 'pandas.core.series.Series'>

In [7]:
# 인덱스
import pandas as pd 
dict_data = {"a":1, "b":2 , "c":3}
sr = pd.Series(dict_data)   
# 인덱스
print(sr.index)

Index(['a', 'b', 'c'], dtype='object')

In [8]:
# 정수형 위치 인덱스
import pandas as pd 
# 리스트 만들기
list_a = ['2023-04-21',3.14,'Hello',10,True]
print(list_a)

['2023-04-21', 3.14, 'Hello', 10, True]

In [10]:
# 시리즈 만들기
sr=pd.Series(list_a)
print(sr)

0    2023-04-21
1          3.14
2         Hello
3            10
4          True
dtype: object

In [11]:
# 인덱스를 이용한 원소 선택
import pandas as pd
# 튜플 만들기
tuple_data = ("정대만","2023-04-01","남",True)
print(tuple_data)

('정대만', '2023-04-01', '남', True)

In [12]:
# 시리즈 만들기
sr=pd.Series(tuple_data, index=["이름","날짜","성별","상남자여부"])
print(sr)

이름              정대만
날짜       2023-04-01
성별                남
상남자여부          True
dtype: object

In [13]:
# 인덱스 이용
# 하나의 원소 선택
print(sr[3])
print(sr[0])
print(sr["상남자여부"])
print(sr["이름"])

True
정대만
True
정대만

In [15]:
# 여러 개의 원소 선택
print(sr[[0,3]])
print(sr[[0,1,3]])
print("\t")
print(sr[["이름","상남자여부"]])
print("\t")
print(sr[["이름","날짜","상남자여부"]])

이름        정대만
상남자여부    True
dtype: object
이름              정대만
날짜       2023-04-01
상남자여부          True
dtype: object

이름        정대만
상남자여부    True
dtype: object

이름              정대만
날짜       2023-04-01
상남자여부          True
dtype: object

In [18]:
# 여러 개의 원소 선택 with 범위 (슬라이싱)
print(sr[1:2+1])
print(sr[1:3])
print(sr[1:3])
print(sr["날짜":"성별"])

날짜    2023-04-01
성별             남
dtype: object
날짜    2023-04-01
성별             남
dtype: object
날짜    2023-04-01
성별             남
dtype: object
날짜    2023-04-01
성별             남
dtype: object

In [20]:
# 데이터 프레임
import pandas as pd 
# 딕셔너리 만들기
dict_data = {"c1":[1,2,3],
"c2":[4,5,6],
"c3":[7,8,9],
"c4":[10,11,12]}
print(dict_data)

{'c1': [1, 2, 3], 'c2': [4, 5, 6], 'c3': [7, 8, 9], 'c4': [10, 11, 12]}

In [21]:
# 데이터프레임 만들기
df = pd.DataFrame(dict_data)    
print(df)

   c1  c2  c3  c4
0   1   4   7  10
1   2   5   8  11
2   3   6   9  12

In [23]:
# 행 인덱스 / 열 이름 설치
import pandas as pd 
# 데이터 프레임 만들기
df = pd.DataFrame([["정대만","남",19],["서태웅","남",17]],
                   index = ["선수1","선수2"],
                   columns = ["이름","성별","나이"])
print(df)

      이름 성별  나이
선수1  정대만  남  19
선수2  서태웅  남  17

In [25]:
# 행 인덱스, 열 이름 확인
df.index=["학생1","학생2"]
df.columns=["성명","남여","연령"]
print(df.index)
print(df.columns)
# rename
print(df)

Index(['학생1', '학생2'], dtype='object')
Index(['성명', '남여', '연령'], dtype='object')
      성명 남여  연령
학생1  정대만  남  19
학생2  서태웅  남  17

In [27]:
# 열 이름
df.rename(columns={"성명":"이름","남여":"성별"}, inplace= True)
# 행 인덱스 변경
df.rename(index={"학생1":"선수1","학생2":"선수2"}, inplace= True)
# 원본 확인
print(df)

      이름 성별  연령
선수1  정대만  남  19
선수2  서태웅  남  17

In [39]:
# 행/열 삭제
import pandas as pd
# 데이터프레임 만들기
# 딕셔너리 => 데이터프레임
exam_data = {'국어':[100,50,80],
             '영어':[80,90,40],
             '수학':[60,40,50],
             '과학':[80,60,70]}
print(exam_data)
df = pd.DataFrame(exam_data,index=["서준","서진","서영"])
print(df)

{'국어': [100, 50, 80], '영어': [80, 90, 40], '수학': [60, 40, 50], '과학': [80, 60, 70]}
     국어  영어  수학  과학
서준  100  80  60  80
서진   50  90  40  60
서영   80  40  50  70

In [40]:
# 복사본
df1 = df[:]
# 행 삭제
df1.drop('서진',inplace = True)
# df1.drop('서진',axis=0)
print(df1)

     국어  영어  수학  과학
서준  100  80  60  80
서영   80  40  50  70

<ipython-input-40-a508d80a1291>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop('서진',inplace = True)

In [42]:
# 열 삭제
df2 = df[:]
df2.drop('과학',axis=1,inplace = True)
print(df2)

     국어  영어  수학
서준  100  80  60
서진   50  90  40
서영   80  40  50

<ipython-input-42-fd8fe16cd2d0>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop('과학',axis=1,inplace = True)

In [44]:
df3 = df[:]
# 여러 개의 행 삭제
df3.drop(["서진","서진"],axis=0,inplace=True)
# 여러 개의 열 삭제
df3.drop(["국어","수학"],axis=1,inplace=True)
print(df3)

    영어  과학
서준  80  80
서영  40  70

<ipython-input-44-e7f647bbeff5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.drop(["서진","서진"],axis=0,inplace=True)
<ipython-input-44-e7f647bbeff5>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.drop(["국어","수학"],axis=1,inplace=True)

In [47]:
# 같은 결과값 (복사본 만드는 방법2)
df3 = df.copy()
# 여러 개의 행 삭제
df3.drop(["서진","서진"],axis=0,inplace=True)
# 여러 개의 열 삭제
df3.drop(["국어","수학"],axis=1,inplace=True)
print(df3)

    영어  과학
서준  80  80
서영  40  70

In [61]:
# 행 선택
exam_data = {'국어':[100,50,80],
             '영어':[80,90,40],
             '수학':[60,40,50],
             '과학':[80,60,70]}
df=pd.DataFrame(exam_data,index=["서준","서진","서영"])
print(df)
# 행 하나를 선택
# loc => 인덱스 이름
name1 = df.loc['서영']
print(name1)
# iloc => 인덱스 숫자
no1 = df.iloc[2]
print(no1)

# 2개 이상의 행 선택
name2 = df.loc[["서준","서진"]]
print(name2)
no2 = df.iloc[[0,1]]
print(no2)

# 행 인덱스 범위 지정하여 선택
name3 = df.loc["서진":"서영"]
print(name3)
no3 = df.iloc[1:3]
print(no3)

     국어  영어  수학  과학
서준  100  80  60  80
서진   50  90  40  60
서영   80  40  50  70
국어    80
영어    40
수학    50
과학    70
Name: 서영, dtype: int64
국어    80
영어    40
수학    50
과학    70
Name: 서영, dtype: int64
     국어  영어  수학  과학
서준  100  80  60  80
서진   50  90  40  60
     국어  영어  수학  과학
서준  100  80  60  80
서진   50  90  40  60
    국어  영어  수학  과학
서진  50  90  40  60
서영  80  40  50  70
    국어  영어  수학  과학
서진  50  90  40  60
서영  80  40  50  70

In [60]:
# 열 선택
print(df)
# 하나의 열 선택
df1 = df["영어"] # 시리즈
df2 = df[["영어"]] # 데이터프레임
print(df1);print(df2)
print(type(df1));print(type(df2))
# 여러 개의 열 선택
df3 = df[["국어","수학"]]
print(df3)

     국어  영어  수학  과학
서준  100  80  60  80
서진   50  90  40  60
서영   80  40  50  70
서준    80
서진    90
서영    40
Name: 영어, dtype: int64
    영어
서준  80
서진  90
서영  40
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
     국어  수학
서준  100  60
서진   50  40
서영   80  50

In [51]:
# 원소 선택
print(df)
# 원소 1개 선택 = 행1 열1
# loc 이름
# 서영의 국어 점수
print(df.loc["서영",["국어","수학"]])
# iloc 번호
df.iloc[2,2:4]

     국어  영어  수학  과학
서준  100  80  60  80
서진   50  90  40  60
서영   80  40  50  70
국어    80
수학    50
Name: 서영, dtype: int64

수학    50
과학    70
Name: 서영, dtype: int64

In [58]:
# 원소 2개 선택 = 행1 열2 with 범위 지정
# 서영이의 수학, 과학 점수
# loc 이름
print(df.loc["서영", "수학":"과학"])
# iloc 번호
print(df.iloc[2,2:4])
print(df.iloc[2,2:])
# 원소 여러 개 선택 = 행2 열2
# 서준, 서영이의 영어, 과학 점수
print(df.loc[["서준","서영"],["영어","과학"]])
print(df.iloc[[0,2],[1,3]])
# 범위 지정 : 서진, 서영이의 수학, 과학
print(df.loc["서진":"서영","수학":"과학"])
print(df.iloc[1:3,2:4])

수학    50
과학    70
Name: 서영, dtype: int64
수학    50
과학    70
Name: 서영, dtype: int64
수학    50
과학    70
사회    90
체육    70
Name: 서영, dtype: int64
    영어  과학
서준  80  80
서영  40  70
    영어  과학
서준  80  80
서영  40  70
    수학  과학
서진  40  60
서영  50  70
    수학  과학
서진  40  60
서영  50  70

In [62]:
# 열 추가
print(df)
# 사회 과목 추가
df["사회"]=90
print(df)
# 체육 과목 추가
df["체육"] = [60,50,70]
print(df)

     국어  영어  수학  과학
서준  100  80  60  80
서진   50  90  40  60
서영   80  40  50  70
     국어  영어  수학  과학  사회
서준  100  80  60  80  90
서진   50  90  40  60  90
서영   80  40  50  70  90
     국어  영어  수학  과학  사회  체육
서준  100  80  60  80  90  60
서진   50  90  40  60  90  50
서영   80  40  50  70  90  70

In [71]:
# 행 추가
print(df)
# 같은 값을 가지고 있는 행 추가
df.loc["진우"] = 0
print(df)
# 여러 개의 값을 가지고 있는 행 추가
df.loc["민종"] = [90,90,90,100,80,90]

       국어    영어    수학     과학    사회    체육     0     1
서준  100.0  80.0  60.0   80.0  90.0  60.0   NaN   NaN
서진   50.0  90.0  40.0   60.0  90.0  50.0   NaN   NaN
서영   80.0  40.0  50.0   70.0  90.0  70.0   NaN   NaN
진우   60.0  70.0  80.0   80.0  80.0  70.0   NaN   NaN
민종   90.0  90.0  90.0  100.0  80.0  90.0   NaN   NaN
3     NaN   NaN   NaN    NaN   NaN   NaN  60.0  70.0
       국어    영어    수학     과학    사회    체육     0     1
서준  100.0  80.0  60.0   80.0  90.0  60.0   NaN   NaN
서진   50.0  90.0  40.0   60.0  90.0  50.0   NaN   NaN
서영   80.0  40.0  50.0   70.0  90.0  70.0   NaN   NaN
진우    0.0   0.0   0.0    0.0   0.0   0.0   0.0   0.0
민종   90.0  90.0  90.0  100.0  80.0  90.0   NaN   NaN
3     NaN   NaN   NaN    NaN   NaN   NaN  60.0  70.0

ValueError: ignored

In [69]:
# 원소 변경
print(df)
# 진우의 체육 점수를 변경
df.loc["진우","체육"] = 70
print(df)
# 진우의 사회 점수를 변경
df.iloc[3,4] = 80
print(df)
# 진우의 수학, 과학 점수를 변경
df.loc["진우",["수학","과학"]] = 80
print(df)
# 진우의 국어, 영어 점수를 변경
df.iloc[3,[0,1]] = 60, 70
print(df)

       국어    영어    수학     과학    사회    체육     0     1
서준  100.0  80.0  60.0   80.0  90.0  60.0   NaN   NaN
서진   50.0  90.0  40.0   60.0  90.0  50.0   NaN   NaN
서영   80.0  40.0  50.0   70.0  90.0  70.0   NaN   NaN
진우   60.0  70.0  80.0   80.0  80.0  70.0   NaN   NaN
민종   90.0  90.0  90.0  100.0  80.0  90.0   NaN   NaN
3     NaN   NaN   NaN    NaN   NaN   NaN  60.0  70.0
       국어    영어    수학     과학    사회    체육     0     1
서준  100.0  80.0  60.0   80.0  90.0  60.0   NaN   NaN
서진   50.0  90.0  40.0   60.0  90.0  50.0   NaN   NaN
서영   80.0  40.0  50.0   70.0  90.0  70.0   NaN   NaN
진우   60.0  70.0  80.0   80.0  80.0  70.0   NaN   NaN
민종   90.0  90.0  90.0  100.0  80.0  90.0   NaN   NaN
3     NaN   NaN   NaN    NaN   NaN   NaN  60.0  70.0
       국어    영어    수학     과학    사회    체육     0     1
서준  100.0  80.0  60.0   80.0  90.0  60.0   NaN   NaN
서진   50.0  90.0  40.0   60.0  90.0  50.0   NaN   NaN
서영   80.0  40.0  50.0   70.0  90.0  70.0   NaN   NaN
진우   60.0  70.0  80.0   80.0  80.0  70.0   NaN   NaN
민종   90.0  90.0  90.0  100.0  80.0  90.0   NaN   NaN
3     NaN   NaN   NaN    NaN   NaN   NaN  60.0  70.0
       국어    영어    수학     과학    사회    체육     0     1
서준  100.0  80.0  60.0   80.0  90.0  60.0   NaN   NaN
서진   50.0  90.0  40.0   60.0  90.0  50.0   NaN   NaN
서영   80.0  40.0  50.0   70.0  90.0  70.0   NaN   NaN
진우   60.0  70.0  80.0   80.0  80.0  70.0   NaN   NaN
민종   90.0  90.0  90.0  100.0  80.0  90.0   NaN   NaN
3     NaN   NaN   NaN    NaN   NaN   NaN  60.0  70.0
       국어    영어    수학     과학    사회    체육     0     1
서준  100.0  80.0  60.0   80.0  90.0  60.0   NaN   NaN
서진   50.0  90.0  40.0   60.0  90.0  50.0   NaN   NaN
서영   80.0  40.0  50.0   70.0  90.0  70.0   NaN   NaN
진우   60.0  70.0  80.0   80.0  80.0  70.0   NaN   NaN
민종   90.0  90.0  90.0  100.0  80.0  90.0   NaN   NaN
3     NaN   NaN   NaN    NaN   NaN   NaN  60.0  70.0

In [70]:
# 행과 열 바꾸기 = 전치
print(df)
print(df.transpose)
print(df.T)

       국어    영어    수학     과학    사회    체육     0     1
서준  100.0  80.0  60.0   80.0  90.0  60.0   NaN   NaN
서진   50.0  90.0  40.0   60.0  90.0  50.0   NaN   NaN
서영   80.0  40.0  50.0   70.0  90.0  70.0   NaN   NaN
진우   60.0  70.0  80.0   80.0  80.0  70.0   NaN   NaN
민종   90.0  90.0  90.0  100.0  80.0  90.0   NaN   NaN
3     NaN   NaN   NaN    NaN   NaN   NaN  60.0  70.0
<bound method DataFrame.transpose of        국어    영어    수학     과학    사회    체육     0     1
서준  100.0  80.0  60.0   80.0  90.0  60.0   NaN   NaN
서진   50.0  90.0  40.0   60.0  90.0  50.0   NaN   NaN
서영   80.0  40.0  50.0   70.0  90.0  70.0   NaN   NaN
진우   60.0  70.0  80.0   80.0  80.0  70.0   NaN   NaN
민종   90.0  90.0  90.0  100.0  80.0  90.0   NaN   NaN
3     NaN   NaN   NaN    NaN   NaN   NaN  60.0  70.0>
       서준    서진    서영    진우     민종     3
국어  100.0  50.0  80.0  60.0   90.0   NaN
영어   80.0  90.0  40.0  70.0   90.0   NaN
수학   60.0  40.0  50.0  80.0   90.0   NaN
과학   80.0  60.0  70.0  80.0  100.0   NaN
사회   90.0  90.0  90.0  80.0   80.0   NaN
체육   60.0  50.0  70.0  70.0   90.0   NaN
0     NaN   NaN   NaN   NaN    NaN  60.0
1     NaN   NaN   NaN   NaN    NaN  70.0

In [73]:
# 인덱스 활용
# 특정 열을 행 인덱스로 설정
import pandas as pd
slamdunk = {"이름":["정대만","강백호","채치수"],
            "키":[183,189,193],
            "나이":[19,17,19],
            "평균득점":[25,5,15]}
df = pd.DataFrame(slamdunk)
print(df)

    이름    키  나이  평균득점
0  정대만  183  19    25
1  강백호  189  17     5
2  채치수  193  19    15

In [75]:
# 이름을 행 인덱스로 설정
df1=df.set_index(["이름"])
print(df1)

       키  나이  평균득점
이름
정대만  183  19    25
강백호  189  17     5
채치수  193  19    15

In [77]:
# 키 행 인덱스로 설정
# 기존의 인덱스가 사라짐
df2=df.set_index(["키"])
print(df2)

      이름  나이  평균득점
키
183  정대만  19    25
189  강백호  17     5
193  채치수  19    15

In [78]:
# 키 행 인덱스로 설정
# 기존의 인덱스가 사라짐
print(df.set_index(["키"]))
df2 = df.set_index(["나이","평균득점"])
print(df2)

      이름  나이  평균득점
키
183  정대만  19    25
189  강백호  17     5
193  채치수  19    15
          이름    키
나이 평균득점
19 25    정대만  183
17 5     강백호  189
19 15    채치수  193

In [99]:
# 행 인덱스 재배열
import pandas as pd 
dict_data = {"c0":[1,2,3],
             "c1":[4,5,6],
             "c2":[7,8,9],
             "c3":[10,11,12],
             "c4":[13,14,15]}
df=pd.DataFrame(dict_data, index = ["r0","r1","r2"])
print(df)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [100]:
# 행 인덱스 재배열
df1=df.reindex(["r0","r1","r2","r3","r4"])
print(df1)
df2=df.reindex(["r0","r1","r2","r3","r4"],fill_value = 0)
print(df2)

     c0   c1   c2    c3    c4
r0  1.0  4.0  7.0  10.0  13.0
r1  2.0  5.0  8.0  11.0  14.0
r2  3.0  6.0  9.0  12.0  15.0
r3  NaN  NaN  NaN   NaN   NaN
r4  NaN  NaN  NaN   NaN   NaN
    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
r3   0   0   0   0   0
r4   0   0   0   0   0

In [101]:
# 행 인덱스 초기화
# 기존의 인덱스가 새로운 열로 추가
print(df)
df3 = df.reset_index()
print(df3)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
  index  c0  c1  c2  c3  c4
0    r0   1   4   7  10  13
1    r1   2   5   8  11  14
2    r2   3   6   9  12  15

In [102]:
# 행 인덱스 정렬
print(df)
df4=df.sort_index(ascending=False) # 내림차순
print(df4)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

In [103]:
# 열 기준 정렬 = 열이 가지고 있는 값으로 정렬
print(df)
df5 = df.sort_values(by = "c1", ascending= False)
print(df5)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13